/**
 * @file prompt_mutator.hpp
 * @brief Derivative-Free Prompt & Token Perturbation Engine Header for blackbox-sec
 * @author Kamran Saberifard
 * @license Apache 2.0
 */

#pragma once

#include <blackbox/blackbox.hpp>

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>
#include <unordered_map>
#include <memory>
#include <mutex>
#include <random>
#include <span>

namespace blackbox::adversarial {

/**
 * @brief Configuration parameters for prompt perturbation operations.
 */
struct BLACKBOX_API PerturbationConfig {
    double perturbation_rate{0.15};      // Maximum percentage of characters/words to mutate
    bool enable_homoglyphs{true};         // Insert Cyrillic/Greek lookalike homoglyphs
    bool enable_zero_width_insertion{true};// Insert invisible zero-width spaces (\u200B)
    bool enable_token_swaps{true};        // Swap synonymous words
    bool enable_framing_injection{true};  // Prepend/append adversarial role-play framing
};

/**
 * @brief Result payload returned after applying a perturbation to a base prompt.
 */
struct BLACKBOX_API PerturbedPromptResult {
    std::string base_prompt;
    std::string perturbed_prompt;
    std::vector<std::string> applied_mutations;
    double edit_distance_ratio{0.0};
};

/**
 * @brief Thread-Safe Derivative-Free Prompt & Token Perturbation Engine.
 */
class BLACKBOX_API PromptMutator {
public:
    explicit PromptMutator(const PerturbationConfig& config = PerturbationConfig{});
    ~PromptMutator() = default;

    // Default copy/move
    PromptMutator(const PromptMutator&) = default;
    PromptMutator& operator=(const PromptMutator&) = default;
    PromptMutator(PromptMutator&&) noexcept = default;
    PromptMutator& operator=(PromptMutator&&) noexcept = default;

    /**
     * @brief Maps a continuous d-dimensional vector x in [-1, 1]^d to discrete prompt mutations.
     * @param base_prompt Original prompt string view.
     * @param continuous_vector Continuous point vector generated by TuRBO or CMA-ES.
     * @return PerturbedPromptResult containing mutated prompt text and mutation logs.
     */
    [[nodiscard]] PerturbedPromptResult perturb_from_vector(
        std::string_view base_prompt, 
        std::span<const double> continuous_vector
    ) const;

    /**
     * @brief Applies stochastic derivative-free mutations to a base prompt.
     * @param base_prompt Original prompt string view.
     * @param rate Perturbation rate modifier (default: config rate).
     * @return PerturbedPromptResult containing mutated prompt text.
     */
    [[nodiscard]] PerturbedPromptResult mutate_random(
        std::string_view base_prompt, 
        double rate = 0.15
    ) const;

    /**
     * @brief Prepends/appends adversarial role-play framing to a prompt.
     * @param base_prompt Original prompt string view.
     * @param framing_index Index selecting specific framing template.
     * @return Framed prompt string.
     */
    [[nodiscard]] static std::string apply_adversarial_framing(
        std::string_view base_prompt, 
        size_t framing_index = 0
    );

    [[nodiscard]] const PerturbationConfig& config() const noexcept { return m_config; }

private:
    PerturbationConfig m_config;
    mutable std::mutex m_mutex;
    mutable std::mt19937 m_rng;

    static const std::vector<std::string> s_framing_templates;
    static const std::unordered_map<char, std::vector<std::string>> s_homoglyph_substitutions;
};

} // namespace blackbox::adversarial